openapi: "3.0.3"

info:
  title: "Nissmick API"
  version: "0.0.0"
servers:
  - url: https://nissmick.net/api/v1
tags:
  - name: "users"
    description: "ユーザー関連"
paths:
  "/users/{id}/display_name":
    get:
      summary: "display_nameを取得"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "nissmick"